### ISSUE TITLE
Subplot axes

### ISSUE THREAD

**Issue by lorendoyle** [lorendoyle/clim680#4]
I need to fix my subplots so that there are only 7 visible.

**Comment by luisortizuriarte** [comment]
You can explore a variety of options here. For example, you can remove the "axis" of the extra subplots directly (using axis('off') method of the ax object). You could also try creating only the subplots you will need one by one in your loop rather than relying on plt.subplots, which creates one subplot for each row/column element.

**Comment by lorendoyle** [comment]
I was able to correct this using .set_axis_off().
