### ISSUE TITLE
Precipitation Colormap

### ISSUE THREAD

**Issue by lorendoyle** [lorendoyle/clim680#5]
I want to find a better colormap than "plasma". It is sequential, so that is okay, but the low color feels too dark, and it interferes with the coastlines and state lines on the contour map.

**Comment by luisortizuriarte** [comment]
You have several options here. You can experiment with the default sequential colormaps in matplotlib (https://matplotlib.org/stable/tutorials/colors/colormaps.html#sphx-glr-tutorials-colors-colormaps-py) to see if any are better suited to your data. Alternately, you may choose to create your own customized colormap (https://matplotlib.org/stable/tutorials/colors/colormap-manipulation.html) by specifying colors or a color palette. Seaborn, which we spoke about briefly yesterday has a handy tool for this as well (https://seaborn.pydata.org/tutorial/color_palettes.html). Finally, if the issue is lack of contrast with the coastlines, would a simple solution be changing their color?

**Comment by lorendoyle** [comment]
I chose the viridis colormap because it is sequential, and the default colormap.
