### ISSUE TITLE
[Assignment 3] Selection of HA phases?

### ISSUE THREAD

**Issue by luisortizuriarte** [lorendoyle/clim680#9]
It is unclear why you chose certain thresholds for your index. From In [22]:

```
august=ha_anoms['ha'].where(ha_anoms['ha']<=4)
september=ha_anoms['ha'].where(ha_anoms['ha']<=6)
october=ha_anoms['ha'].where(ha_anoms['ha']>=3)
``` 

What is the relevance of these thresholds? Also, the values picked up by your comparisons will have various overlaps. For example, values <=6 (september) will also include all values <=4 (august).

**Comment by pdirmeyer** [comment]
I had the same question.  With only 6 years, it will probably be hard to pull out much signal about interannual variability, the sample size being so small, but it might make more sense to composite the 3 largest vs 3 smallest valued years for ha for each month.

**Comment by lorendoyle** [comment]
I changed my composites to do the 3 largest and 3 smallest valued hurricane activity years. On my first homework attempt, I was a bit confused on what a composite actually was, and how I would perform one with my dataset. But, I figured it out. I was trying to redo what we did in class, however the index I chose is not oscillatory (it does not go below 0), so I was trying to do it as selecting the number of storms on average per month and if the index exceeded or dipped below that average number, but I could not figure out how to do that, which is why the composites do not make sense. In the updated notebooks, I just did not attempt to do that, and instead did composites based off of the index itself.
